[package]
name = "d64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name="dump_disk"

[[example]]
name="rename_disk"

[[example]]
name="format_disk"


[dependencies]
