[package]
name = "petscii"
version = "0.1.0"
authors = ["Jeroen Bakker<j.bakker@atmind.nl>"]
edition = "2021"

description = "Crate to encode and decode Petscii char set."
repository = "https://github.com/jeroenbakker-atmind/d64-rs"
